name: Deploy registry to Cloudflare Pages

on:
    push:
        branches: ['main']
        paths:
            - 'apps/registry/**'
    pull_request:
        branches: ['main']
        paths:
            - 'apps/registry/**'

permissions:
    contents: read
    deployments: write

jobs:
    deploy:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [20]

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
              env:
                  PUBLIC_BACKEND_URL: ${{ vars.PUBLIC_BACKEND_URL }}

            - name: Deploy to Cloudflare Pages
              uses: cloudflare/wrangler-action@v3
              with:
                  packageManager: pnpm
                  apiToken: ${{ secrets.CLOUDFLARE_VR_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy apps/registry/dist --project-name=vayload-registry
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
